### ISSUE TITLE
Multiple Errors with Laravel 4

### ISSUE THREAD

**Issue by dbhurley** [Chumper/Zipper#11]
Not sure what might be going wrong. I added the service provider to my config and yet 

```$zipper = new Zipper;```

Yields an error on "undefined method make"

If I use 

```$zipper = new \Chumper\Zipper\Zipper```

I receive an error on "fatal error cannot call each() on undefined"

If I copy and paste the "sample" code I get a failure on ->close() in the deconstructor

Any ideas what I'm doing wrong?

**Comment by ctf0** [comment]
@dbhurley try to add `'Zipper'  => 'Chumper\Zipper\Zipper'` to aliases and it should work.
