### ISSUE TITLE
Class 'Zipper' not found

### ISSUE THREAD

**Issue by shankhadevpadam** [Chumper/Zipper#110]
I have configure the package using the readme file with Ubuntu 16.04 with php 7.0.22. What is my problem ?. I think facade not working with laravel 5.4

**Comment by ozldmezot** [comment]
The README doesnt say anything about facades, however since it has a Service Provider and a Facade it is supported, please check if you have configured it correctly, it should look like this:

```
'providers' = [
    ...
    Chumper\Zipper\ZipperServiceProvider::class,
    ...
],
...
'aliases' => [
    'Zipper'  => Chumper\Zipper\Facades\Zipper::class,
],
...
```

**Comment by johannesschobel** [comment]
@shankhadevpadam can this issue be closed?
