### ISSUE TITLE
Call to a member function addFile() on a non-object

### ISSUE THREAD

**Issue by sil218** [Chumper/Zipper#15]
Hello, I can use the package on local XAMPP, however, when I use it on the server, I am getting this error at line 365 (/vendor/chumper/zipper/src/Chumper/Zipper/Zipper.php)

$this->repository->addFile($pathToAdd, $this->getInternalPath() . $file_name);

how to fix this problem?

**Comment by Chumper** [comment]
Are there still problems with this? If so i need to take another look.

**Comment by vektrom** [comment]
Hello,

I'm getting the following error: **Call to a member function each() on a non-object**
At **line 405 (/vendor/chumper/zipper/src/Chumper/Zipper/Zipper.php)**

Sorry if I should have opened a new issue instead post it here.
