### ISSUE TITLE
Service provider not deferred

### ISSUE THREAD

**Issue by lonnylot** [Chumper/Zipper#17]
The `package` method (called in `boot`) does a lot of file/directory checks when it is called. If you have an app that does a lot of things NOT related to Zipper this will cause a problem. Would it be possible to set the service provider to be deferred?

**Comment by Chumper** [comment]
I havent done anything laravel related latley, if you give me a link to some documentation, i will try to do my best.

**Comment by lonnylot** [comment]
I actually meant to close this. It is a non-issue and I was incorrect.
