### ISSUE TITLE
Call to a member function addFile() on null

### ISSUE THREAD

**Issue by sergiocastrovale** [Chumper/Zipper#26]
Hi, thanks a lot for the package. I'm having some trouble zipping a set of four images. This is done by triggering the saved() event. However, when I do this:

```php
SizeTexture::saved(function($st)
{
	$files = array($st['image_diffuse'], $st['image_nrm'], $st['image_spec'], $st['image_disp']);
	$zipper = new \Chumper\Zipper\Zipper;
	$path = realpath(public_path()) . '/uploads/textures/';

	// We'll create the zip even if we only have one image

	foreach ($files as $file) {
		if ($file != '') {
			$zipper->add($path . $file);
		}
	}

	$zipper->make('file.zip');
});
```

I get the following error:

```php
Call to a member function addFile() on null
```

I'm not entirely sure that this is a problem with the plugin, because my $path points to the full path of the file in my disk, not as a web address (Something like h:\folder\public\uploads\...). Do you have any clues?

Thanks in advance!

**Comment by Chumper** [comment]
You need to call `make()` first. That will create the zip package, then you can add Files and later save it.
I merged a PR with documentation, may you give it a try again.
