### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by ctf0** [Chumper/Zipper#29]
`Zipper::getFileContent('public/test.zip')` 
return NULL

`Zipper::make('public/test.zip')->folder('comp')->remove('composer.lock')->close()` 
return NULL

`Zipper::make('public/test.zip')->extractTo('public/_new/', ['comp'], Zipper::BLACKLIST)` Undefined class constant 'BLACKLIST'

**Comment by Chumper** [comment]
Do you use Laravel?
How do you create Zipper?

**Comment by ctf0** [comment]
yes ,thought laravel providers & aliases ?

**Comment by Chumper** [comment]
Ok, you create or open a zip always with the `make` method which will try to guess the underlaying engine or diectly with `zip`

The second example should work if you have an existing zip, where do you get the null?

With the third example i dont know how you included the Zipper class, but if you have access to `make` you should also have acess to the `BLACKLIST` constant

**Comment by ctf0** [comment]
the first one i use `Zipper::getFileContent('public/files/_test.zip');` and i get 
```Call to a member function fileExists() on null```

the second the solution was to remove `close()` ,because zipper does that automatically.

the third have 2 parts
- when something like `Zipper::make('public/files/_test.zip')->folder('comp')->extractTo('public/files/new');` i get `mkdir(): Invalid path` ,basically u cant make a new folder instead u have to use an existing one.

- as `Zipper::BLACKLIST` is the default for that function so not adding it does the expected ,but other than that it still gives the same error.

a new one  `Zipper::getStatus('public/files/_test.zip');` which gives 
```Call to a member function getStatus() on null```

**Comment by Chumper** [comment]
The first command always needs to be a `zip` or `make` otherwise the class does not know which while to work on or which file to create.
As i could not use the constructor, because the class is already initialized i need to create a new function for that.

So your first example should be: 
```php
Zipper::zip('public/files/_test.zip')->doYourStuff();
```

The third example in the first part that could be considered as a bug.

Your last example should be
```php
Zipper::zip('public/files/_test.zip')->getStatus();
```

**Comment by ctf0** [comment]
i tried `Zipper::make('public/files/_test.zip')->getFileContent()` and got
```Missing argument 1 for Chumper\Zipper\Zipper::getFileContent()```
with `dd(Zipper::make($z)->getStatus())` i always get `string(8) "No error"` even if the file is not found.

**Comment by Chumper** [comment]
`Zipper::zip($z)->getStatus()` will create a new zip if it is not found, therefore it is normal that `getStatus()` returns no error.

`Zipper::zip('public/files/_test.zip')->getFileContent(yourFileInTheZip)` thats how it works, it gives the content of a file in the zip.

What do you want to do? If you want the whole zip, just use the Filesystem methods.

**Comment by ctf0** [comment]
i thought the `getFileContent` display like an array of the files in the zip.

**Comment by Chumper** [comment]
Then just use the `listFiles()` function.

**Comment by ctf0** [comment]
actually that function is not in the readme ,thats why i had no clue about it ,thanx for ur help :+1: .

**Comment by Chumper** [comment]
you are right, it should be documented i think ;)

**Comment by tamaghna91** [comment]
I am trying to find files under one level directory that means my root is src->controller->mycontroller.php and which I want to extract under laravel app/Http/Controllers folder, so far extracted and tried from the above discussions - `dd(Zipper::zip($plugin_path)->getFileContent('controller'));`

**Comment by vicky596** [comment]
Hello Sir , I am getting  class Zipper not found.
I am using Laravel 5.3 and PHP 7
and in my  "composer.json" 
allready written "chumper/zipper": "^1.0",

and in config->app.php
wrote by me
'provider =>'[
----
Chumper\Zipper\ZipperServiceProvider::class,
]

aliases =>[
----
 'Zipper' => Chumper\Zipper\Zipper::class,

]
and execute the "composer update"

and accessing then  got class Zipper not found.
where i am wrong
