### ISSUE TITLE
Subfolder

### ISSUE THREAD

**Issue by YavuzSahin** [Chumper/Zipper#30]
$zipper->folder("foldername")->folder("subfoldername")->add("file") not working. how to create subfolder or child folder?

**Comment by Chumper** [comment]
If you use `folder` you pass the absolute path, not the relative one.
```php
$zipper->folder("foldername/subfoldername")->add("file")
```
This should put the file in the folder subfoldername if i am not mistaken.

**Comment by YavuzSahin** [comment]
hey! i know, you don't mistake. this is okay working thank you very much :)
