### ISSUE TITLE
Add folder + subdirectories in windows environment

### ISSUE THREAD

**Issue by plantwebdesign** [Chumper/Zipper#33]
I am having trouble adding a folder to a zip archive on a windows machine. It adds the files from within the folder, but does not recurse through to subdirectories...

I think it may be to do with backslash / forward slash mixing, but I am not entirely sure.

Any ideas?

**Comment by Chumper** [comment]
You can try a temporary fix with replacing all `/` with `DIRECTORY_SEPARATOR`.
If that works you can submit a PR and i will merge it.

**Comment by plantwebdesign** [comment]
I thought about that and tried it, but no joy. I am having a good look at it this morning. If I manage to get it sorted, I'll post back.

**Comment by plantwebdesign** [comment]
I found the problem. It was related to the currentFolder beginning with a '/'.

I simply needed to modify Zipper.php line 363 to read:

```
$this->currentFolder = empty($this->currentFolder) ? basename($dir) : $this->currentFolder . '/' . basename($dir);
```

Can't see any problems with that fix as it is confined to the addDir function. Created zip then works fine on both Windows and OSX.

**Comment by thecotne** [comment]
i can confirm that on windows 10 32bit (i guess in other windows versions also) 
this bug is fixed

@plantwebdesign close this issue and thx for fixing
