### ISSUE TITLE
please create laravel 5 branch

### ISSUE THREAD

**Issue by thecotne** [Chumper/Zipper#35]
i will fix all the bugs in laravel 5 branch
i have project that is in laravel 5 and i want to use this package

it will be grate if you add me in contributors or i will create pull requests

**Comment by Chumper** [comment]
i have created `develop-l5` where you can create PRs to

**Comment by thecotne** [comment]
we need 2 branch for laravel 4 and for laravel 5 
laravel 5 version will not work for laravel 4 and 
laravel 4 version will not work for laravel 5 and 

currently master brunch is not compatible with laravel 4 and 5

v0.5.1 is compatible with laravel 4 
but how we will update that ? i guess we need branch with illuminate/support and illuminate/filesystem to 4.x

#34 will make master compatible with laravel 5

**Comment by Chumper** [comment]
i would keep the master branch compatible with L5 and deprecate L4, 
As you said 0.5.1 is compatible with L4 and will be the last version for it.

**Comment by thecotne** [comment]
have you tested current version on L5
it does not work at all
i have pull request #34 
i guess there will be other issue but it makes this simple example work
```php
$files = glob('public/files/*');
Zipper::make('public/test.zip')->add($files);
```

i was thinking we need to support L4
if not develop-l5 branch is useless

also i want to say thank you for this library
it makes world better place :laughing:

**Comment by Chumper** [comment]
ok, i have created l4 and l5 as branches, we just need to put the right versions there

**Comment by thecotne** [comment]
in L4 branch if you remove last 3 commits it will be fine

you said master will be for L5 so we don't need 'l5' branch 
just update readme and say: master branch is for laravel 5 and there is L4 branch if you use laravel 4 click here 
somthing like this

**Comment by thecotne** [comment]
please tag current master branch as 0.6.1

also in readme 
instead of '0.5.1' and '0.6.0' it will be better to put '0.5.*' and '0.6.*' 
because usually last digit is for bug fixes
