### ISSUE TITLE
Issues using 0.6.* in fresh Laravel 5 installation

### ISSUE THREAD

**Issue by lehnen** [Chumper/Zipper#37]
Hy,
I made a fresh Laravel 5 installation. 
I only included "barryvdh/laravel-ide-helper": "~2.0" and "Chumper/Zipper": "0.6.*"
and updated the app.php as described.
Now I got the following error:
![image](https://cloud.githubusercontent.com/assets/897486/6244495/97bfd586-b754-11e4-8521-5a02d23343d6.png)

I also find a small error in your installation description.
You made different installation hints for Laravel 4 / 5 by using 1a and 1b.
Since the location of the app.php has changed I could be helpful to use
2a (app/config/app.php) and 2b (config/app.php)

Thanx for developing the Zipper ;)

**Comment by thecotne** [comment]
this bug is fixed by #34 
try `"Chumper/Zipper": "dev-master"`

i already asked for tagging new version
https://github.com/Chumper/Zipper/issues/35#issuecomment-74560386

**Comment by thecotne** [comment]
@lehnen we have new release `v0.6.1` try and if it is fixed close issues

**Comment by lehnen** [comment]
Great! Seems to work!
Thanx for quick support ;)
