### ISSUE TITLE
v0.6.1 isn't compatible with PHP 5.3.x

### ISSUE THREAD

**Issue by fredleblanc** [Chumper/Zipper#38]
Minimum PHP required on packagist is listed as 5.3.0, but requires `illuminate/support` and `illuminate/filesystem`, both of which have 5.4.0 minimum requirements. Due to *that* code's use of `[]` array shortcuts, using v0.6.1 with PHP 5.3.x results in errors like this:

```
Parse error: syntax error, unexpected '[' in /path/to/app/vendor/illuminate/support/helpers.php on line 351
```

**Comment by thecotne** [comment]
if you are useing laravel 4 you can install "0.5.x" which is laravel 4 compatible
