### ISSUE TITLE
runs as background process - no way to wait for it to be done

### ISSUE THREAD

**Issue by iateadonut** [Chumper/Zipper#54]
I think this runs asynchronously in the background.  In my script, I zip the newly created files before I email them, and I'd like there to be a way to wait for the process to complete.

**Comment by jsartisan** [comment]
same issue. @iateadonut any solution ?

**Comment by pokono** [comment]
I usually put in a while, waiting for the file to exist. Anybody has a better solution?

**Comment by acirinelli** [comment]
Thank you @pokono !! I've been struggling with this issue for over an hour and this seems to have solved it.

**Comment by nicolaeturcan** [comment]
@pokono Thanks you sir!
