### ISSUE TITLE
extractTo() extracts all files that start with given string

### ISSUE THREAD

**Issue by aldas** [Chumper/Zipper#81]
Currently `public function extractTo($path, array $files = array(), $method = Zipper::BLACKLIST)`  parameter `$files` acts as a prefix for files to be blacklisted/whitelisted.

So if your zip contains files

"
...
/folder/somefile.data
/folder/somefile.data.log
/folder/another.data
/folder/another.data.log
...
"

```
$this->zipper->folder('folder')->extractTo(
        $toDirectory, 
        ['somefile.data', 'another.data'], 
        Zipper::WHITELIST
);
```

would extract .log files also.

Maybe this filename matching should be strict or parameter to force exact matches only?

**Comment by Chumper** [comment]
I think it would be a good idea to match only exact. Opinions?

**Comment by aldas** [comment]
well, that prefix feature is handy if you know for sure that, your zip does not contain cases as I displayed. Then you do not need to filter files to build your whitelist array just pass your prefix in array and you are good to go. But there are for sure situations where this startWith feature introduces bugs to your app as you could extract wrong files.

**Comment by Chumper** [comment]
Sounds good, as long as you keep the old method for backward compatibility reasons.
