### ISSUE TITLE
Laravel 5.4 support

### ISSUE THREAD

**Issue by marcoraddatz** [Chumper/Zipper#89]
Hi,

many thanks for providing this package. Unfortunately it doesn't work with Laravel 5.4, as an exception is thrown:

> Call to undefined method Illuminate\Foundation\Application::share()

I see that there's already a PR, but it's not yet released due to failing tests on PHP 5.4 and PHP 5.5. Laravel 5.3+ requires PHP >=5.6.0, so in my opinion old dependencies could be removed?

**Comment by abkrim** [comment]
Problem is 

>share Method Removed

>The share method has been removed from the container. This was a legacy method that has not been >documented in several years. If you are using this method, you should begin using the singleton >method instead:

```php
$container->singleton('foo', function () {
    return 'foo';
});
```

Actual code on ZipperServiceProvider.php
```php
public function register()
    {
        
        $this->app['zipper'] = $this->app->share(function($app)
        {
            $return = $app->make('Chumper\Zipper\Zipper');
            return $return;
        });
```

Must be
```php
public function register()
{
           $this->app->singleton('zipper', function ($app) {
           return  $app->make('Chumper\Zipper\Zipper');
        });

```

**Comment by marcoraddatz** [comment]
True, the latest commit already has the singleton: https://github.com/Chumper/Zipper/commit/35b5b044f424b35c61971f1c8be5505eaa947bae

But here are the tests: https://travis-ci.org/Chumper/Zipper/builds/194994897 — old PHP versions fail.

**Comment by Saradimi** [comment]
Same here

**Comment by Bolandish** [comment]
How does the future looks? Is it going to be fixed ? :)

**Comment by Chumper** [comment]
Drafted a new release without PHP 5.4 and 5.5 support, so i bumped the mayor version up to `1.0.0`

**Comment by Bolandish** [comment]
Good job! Thanks 👍
